# version: '3'
# services:
#   nginx:
#     container_name: nginx
#     build: ./requirements/nginx
#     ports:
#       - 443:443
#     volumes:
#       - nginx-data:/var/log/nginx
#     restart: always
#     networks:
#       - app-network

# volumes:
#   nginx-data:
#   db-data:
#   wp-data:

# networks:
#   app-network:

version: '3'

services:
  nginx:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./requirements/nginx/index.html:/usr/share/nginx/html/index.html:ro
      - ./requirements/nginx/style.css:/usr/share/nginx/html/style.css:ro
