version: '3.3'

volumes:
  wp-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/sdukic/data/wordpress
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/sdukic/data/mariadb


networks:
  custom-network:

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      args:
        WP_URL: ${WP_URL}
        WP_TITLE: ${WP_TITLE}
        WP_ADMIN_LOGIN: ${WP_ADMIN_LOGIN}
        WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
        WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
        WP_USER_LOGIN: ${WP_USER_LOGIN}
        WP_USER_PASSWORD: ${WP_USER_PASSWORD}
        WP_USER_EMAIL: ${WP_USER_EMAIL}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - custom-network
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wp-data:/var/www/html
    networks:
      - custom-network
    restart: unless-stopped

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wp-data:/var/www/html
      - /etc/ssl/certs:/etc/ssl/certs
      - /etc/ssl/private:/etc/ssl/private
    networks:
      - custom-network
    restart: unless-stopped
