CREATE DATABASE IF NOT EXISTS ${WP_TITLE};

CREATE USER IF NOT EXISTS '${WP_USER_LOGIN}'@'%' IDENTIFIED BY '${WP_USER_PASSWORD}';

GRANT ALL PRIVILEGES ON ${WP_TITLE}.* TO '${WP_USER_LOGIN}'@'%';

SET PASSWORD FOR 'root'@'localhost' = '${MYSQL_ROOT_PASSWORD}';
